### ISSUE TITLE
 protein level

### ISSUE THREAD

**Issue by madrox22** [TencentAILabHealthcare/scPROTEIN#1]
Hi, 

How do we go from the "peptide uncertainty" to **protein** level after running scPROTEIN? 

Thanks.

**Comment by weilicode** [comment]
Hi, @madrox22 

After generating the peptide uncertainty with stage1, you can then use the function load_sc_proteomic_features to obtain the protein-level data (also can see our tutorial for stage1: https://github.com/TencentAILabHealthcare/scPROTEIN/blob/main/tutorial_scPROTEIN_stage1.ipynb ). It takes peptide uncertainty and peptide data as input and outputs the protein-level data by uncertainty-guided aggregation.
