### ISSUE TITLE
Non-centralized data

### ISSUE THREAD

**Issue by yzhou1999** [TencentAILabHealthcare/scPROTEIN#4]
Hello,

I noticed that you provided the data from the scPROTEIN paper in this repository. But they seem to be centralized data. Can you please also provide non-centralized data?

Thanks!

**Comment by weilicode** [comment]
Hi @yzhou1999 ,

You can find the raw datasets in the following links:
https://scp.slavovlab.net/Huffman_et_al_2022
https://scp.slavovlab.net/Leduc_et_al_2021
https://scp.slavovlab.net/Specht_et_al_2019
https://scp.slavovlab.net/Derks_et_al_2022

and a well-established single-cell proteomics database:
https://scproteomicsdb.com/

Hope these can help you.
Thanks

**Comment by yzhou1999** [comment]
Hi @nkuweili !
Thanks for your reply, and thanks for your excellent work!

**Comment by weilicode** [comment]
Thanks a lot!
